# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.16
            
    working_directory: /go/src/github.com/danesparza/nws-alerts
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: go mod download

      - run: 
         name: Create the artifacts directory
         command: mkdir -p /tmp/artifacts

      - run: 
         name: Install the Github release creator tool
         command: go get github.com/tcnksm/ghr
   
      - run:
         name: Run tests
         command: go test -v -race github.com/danesparza/nws-alerts/data

      - run:
         name: Build AWS handler
         command: env GOOS=linux go build -ldflags "-X main.BuildVersion=1.0.$CIRCLE_BUILD_NUM -X main.CommitID=$CIRCLE_SHA1" -o nws-alerts main.go

      - run:
         name: Package AWS handler
         command: zip nws-alerts_handler.zip ./nws-alerts

      - run:
         name: Push package to artifacts
         command: mv nws-alerts_handler.zip /tmp/artifacts/

      # Indicate we have artifacts
      - store_artifacts:
          path: /tmp/artifacts

      - run: 
         name: Create a release on Github
         command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v1.0.$CIRCLE_BUILD_NUM /tmp/artifacts || true
